In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_csv('data/Amazon Sale Report.csv')
df.head()

C:\Users\goure\AppData\Local\Temp\ipykernel_30756\867354103.py:1: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('data/Amazon Sale Report.csv')

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,Size,ASIN,Courier Status,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,S,B09KXVBD7Z,NaN,0,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,3XL,B09K3WFS32,Shipped,1,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,XL,B07WV4JV4D,Shipped,1,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,L,B099NRCT7B,NaN,0,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,3XL,B098714BZP,Shipped,1,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN

In [3]:
df.isnull().sum()

index                     0
Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Style                     0
SKU                       0
Category                  0
Size                      0
ASIN                      0
Courier Status         6872
Qty                       0
currency               7795
Amount                 7795
ship-city                33
ship-state               33
ship-postal-code         33
ship-country             33
promotion-ids         49153
B2B                       0
fulfilled-by          89698
Unnamed: 22           49050
dtype: int64

In [4]:
df['Date'].unique()

array(['04-30-22', '04-29-22', '04-28-22', '04-27-22', '04-26-22',
       '04-25-22', '04-24-22', '04-23-22', '04-22-22', '04-21-22',
       '04-20-22', '04-19-22', '04-18-22', '04-17-22', '04-16-22',
       '04-15-22', '04-14-22', '04-13-22', '04-12-22', '04-11-22',
       '04-10-22', '04-09-22', '04-08-22', '04-07-22', '04-06-22',
       '04-05-22', '04-04-22', '04-03-22', '04-02-22', '04-01-22',
       '03-31-22', '05-31-22', '05-30-22', '05-29-22', '05-28-22',
       '05-27-22', '05-26-22', '05-25-22', '05-24-22', '05-23-22',
       '05-22-22', '05-21-22', '05-20-22', '05-19-22', '05-18-22',
       '05-17-22', '05-16-22', '05-15-22', '05-14-22', '05-13-22',
       '05-12-22', '05-11-22', '05-10-22', '05-09-22', '05-08-22',
       '05-07-22', '05-06-22', '05-05-22', '05-04-22', '05-03-22',
       '05-02-22', '05-01-22', '06-29-22', '06-28-22', '06-27-22',
       '06-26-22', '06-25-22', '06-24-22', '06-23-22', '06-22-22',
       '06-21-22', '06-20-22', '06-19-22', '06-18-22', '06-17-22',
       '06-16-22', '06-15-22', '06-14-22', '06-13-22', '06-12-22',
       '06-11-22', '06-10-22', '06-09-22', '06-08-22', '06-07-22',
       '06-06-22', '06-05-22', '06-04-22', '06-03-22', '06-02-22',
       '06-01-22'], dtype=object)

In [5]:
df['Date'] = pd.to_datetime(df['Date'], errors = 'coerce')

C:\Users\goure\AppData\Local\Temp\ipykernel_30756\1953939787.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Date'] = pd.to_datetime(df['Date'], errors = 'coerce')

In [6]:
df['Date'].unique()

<DatetimeArray>
['2022-04-30 00:00:00', '2022-04-29 00:00:00', '2022-04-28 00:00:00',
 '2022-04-27 00:00:00', '2022-04-26 00:00:00', '2022-04-25 00:00:00',
 '2022-04-24 00:00:00', '2022-04-23 00:00:00', '2022-04-22 00:00:00',
 '2022-04-21 00:00:00', '2022-04-20 00:00:00', '2022-04-19 00:00:00',
 '2022-04-18 00:00:00', '2022-04-17 00:00:00', '2022-04-16 00:00:00',
 '2022-04-15 00:00:00', '2022-04-14 00:00:00', '2022-04-13 00:00:00',
 '2022-04-12 00:00:00', '2022-04-11 00:00:00', '2022-04-10 00:00:00',
 '2022-04-09 00:00:00', '2022-04-08 00:00:00', '2022-04-07 00:00:00',
 '2022-04-06 00:00:00', '2022-04-05 00:00:00', '2022-04-04 00:00:00',
 '2022-04-03 00:00:00', '2022-04-02 00:00:00', '2022-04-01 00:00:00',
 '2022-03-31 00:00:00', '2022-05-31 00:00:00', '2022-05-30 00:00:00',
 '2022-05-29 00:00:00', '2022-05-28 00:00:00', '2022-05-27 00:00:00',
 '2022-05-26 00:00:00', '2022-05-25 00:00:00', '2022-05-24 00:00:00',
 '2022-05-23 00:00:00', '2022-05-22 00:00:00', '2022-05-21 00:00:00',
 '2022-05-20 00:00:00', '2022-05-19 00:00:00', '2022-05-18 00:00:00',
 '2022-05-17 00:00:00', '2022-05-16 00:00:00', '2022-05-15 00:00:00',
 '2022-05-14 00:00:00', '2022-05-13 00:00:00', '2022-05-12 00:00:00',
 '2022-05-11 00:00:00', '2022-05-10 00:00:00', '2022-05-09 00:00:00',
 '2022-05-08 00:00:00', '2022-05-07 00:00:00', '2022-05-06 00:00:00',
 '2022-05-05 00:00:00', '2022-05-04 00:00:00', '2022-05-03 00:00:00',
 '2022-05-02 00:00:00', '2022-05-01 00:00:00', '2022-06-29 00:00:00',
 '2022-06-28 00:00:00', '2022-06-27 00:00:00', '2022-06-26 00:00:00',
 '2022-06-25 00:00:00', '2022-06-24 00:00:00', '2022-06-23 00:00:00',
 '2022-06-22 00:00:00', '2022-06-21 00:00:00', '2022-06-20 00:00:00',
 '2022-06-19 00:00:00', '2022-06-18 00:00:00', '2022-06-17 00:00:00',
 '2022-06-16 00:00:00', '2022-06-15 00:00:00', '2022-06-14 00:00:00',
 '2022-06-13 00:00:00', '2022-06-12 00:00:00', '2022-06-11 00:00:00',
 '2022-06-10 00:00:00', '2022-06-09 00:00:00', '2022-06-08 00:00:00',
 '2022-06-07 00:00:00', '2022-06-06 00:00:00', '2022-06-05 00:00:00',
 '2022-06-04 00:00:00', '2022-06-03 00:00:00', '2022-06-02 00:00:00',
 '2022-06-01 00:00:00']
Length: 91, dtype: datetime64[ns]

In [7]:
df['Date'] = df['Date'].dt.date
df['Date'].unique()

array([datetime.date(2022, 4, 30), datetime.date(2022, 4, 29),
       datetime.date(2022, 4, 28), datetime.date(2022, 4, 27),
       datetime.date(2022, 4, 26), datetime.date(2022, 4, 25),
       datetime.date(2022, 4, 24), datetime.date(2022, 4, 23),
       datetime.date(2022, 4, 22), datetime.date(2022, 4, 21),
       datetime.date(2022, 4, 20), datetime.date(2022, 4, 19),
       datetime.date(2022, 4, 18), datetime.date(2022, 4, 17),
       datetime.date(2022, 4, 16), datetime.date(2022, 4, 15),
       datetime.date(2022, 4, 14), datetime.date(2022, 4, 13),
       datetime.date(2022, 4, 12), datetime.date(2022, 4, 11),
       datetime.date(2022, 4, 10), datetime.date(2022, 4, 9),
       datetime.date(2022, 4, 8), datetime.date(2022, 4, 7),
       datetime.date(2022, 4, 6), datetime.date(2022, 4, 5),
       datetime.date(2022, 4, 4), datetime.date(2022, 4, 3),
       datetime.date(2022, 4, 2), datetime.date(2022, 4, 1),
       datetime.date(2022, 3, 31), datetime.date(2022, 5, 31),
       datetime.date(2022, 5, 30), datetime.date(2022, 5, 29),
       datetime.date(2022, 5, 28), datetime.date(2022, 5, 27),
       datetime.date(2022, 5, 26), datetime.date(2022, 5, 25),
       datetime.date(2022, 5, 24), datetime.date(2022, 5, 23),
       datetime.date(2022, 5, 22), datetime.date(2022, 5, 21),
       datetime.date(2022, 5, 20), datetime.date(2022, 5, 19),
       datetime.date(2022, 5, 18), datetime.date(2022, 5, 17),
       datetime.date(2022, 5, 16), datetime.date(2022, 5, 15),
       datetime.date(2022, 5, 14), datetime.date(2022, 5, 13),
       datetime.date(2022, 5, 12), datetime.date(2022, 5, 11),
       datetime.date(2022, 5, 10), datetime.date(2022, 5, 9),
       datetime.date(2022, 5, 8), datetime.date(2022, 5, 7),
       datetime.date(2022, 5, 6), datetime.date(2022, 5, 5),
       datetime.date(2022, 5, 4), datetime.date(2022, 5, 3),
       datetime.date(2022, 5, 2), datetime.date(2022, 5, 1),
       datetime.date(2022, 6, 29), datetime.date(2022, 6, 28),
       datetime.date(2022, 6, 27), datetime.date(2022, 6, 26),
       datetime.date(2022, 6, 25), datetime.date(2022, 6, 24),
       datetime.date(2022, 6, 23), datetime.date(2022, 6, 22),
       datetime.date(2022, 6, 21), datetime.date(2022, 6, 20),
       datetime.date(2022, 6, 19), datetime.date(2022, 6, 18),
       datetime.date(2022, 6, 17), datetime.date(2022, 6, 16),
       datetime.date(2022, 6, 15), datetime.date(2022, 6, 14),
       datetime.date(2022, 6, 13), datetime.date(2022, 6, 12),
       datetime.date(2022, 6, 11), datetime.date(2022, 6, 10),
       datetime.date(2022, 6, 9), datetime.date(2022, 6, 8),
       datetime.date(2022, 6, 7), datetime.date(2022, 6, 6),
       datetime.date(2022, 6, 5), datetime.date(2022, 6, 4),
       datetime.date(2022, 6, 3), datetime.date(2022, 6, 2),
       datetime.date(2022, 6, 1)], dtype=object)

In [8]:
df.head()

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,Size,ASIN,Courier Status,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,S,B09KXVBD7Z,NaN,0,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,2022-04-30,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,3XL,B09K3WFS32,Shipped,1,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,XL,B07WV4JV4D,Shipped,1,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,L,B099NRCT7B,NaN,0,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,3XL,B098714BZP,Shipped,1,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 24 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   index               128975 non-null  int64
 1   Order ID            128975 non-null  object
 2   Date                128975 non-null  object
 3   Status              128975 non-null  object
 4   Fulfilment          128975 non-null  object
 5   Sales Channel       128975 non-null  object
 6   ship-service-level  128975 non-null  object
 7   Style               128975 non-null  object
 8   SKU                 128975 non-null  object
 9   Category            128975 non-null  object
 10  Size                128975 non-null  object
 11  ASIN                128975 non-null  object
 12  Courier Status      122103 non-null  object
 13  Qty                 128975 non-null  int64
 14  currency            121180 non-null  object
 15  Amount              121180 non-null  float64
 16  ship-city           128942 non-null  object
 17  ship-state          128942 non-null  object
 18  ship-postal-code    128942 non-null  float64
 19  ship-country        128942 non-null  object
 20  promotion-ids       79822 non-null   object
 21  B2B                 128975 non-null  bool
 22  fulfilled-by        39277 non-null   object
 23  Unnamed: 22         79925 non-null   object
dtypes: bool(1), float64(2), int64(2), object(19)
memory usage: 22.8+ MB

In [10]:
df.to_csv('data/amazon_sales_report.csv', index = False)

In [11]:
# df['Date'] = pd.to_datetime(df['Date'], errors = 'coerce')

In [12]:
# df['months'] = df['Date'].dt.month_name()

In [13]:
# df.head()

In [14]:
# df['Date'].unique()

In [15]:
# df['months'].unique()

In [16]:
# df.head(5)

In [17]:
# df.drop('Date', axis = 1, inplace = True)

In [18]:
# df.head(5)

In [19]:
# df.to_csv('data/amazon_cleaned_report.csv', index = False)